/** Code-owned provider catalogue for provider-account capabilities. */
export const PROVIDER_PERMISSION_REGISTRY = [
  {
    code: 'provider-account:read',
    name: 'Read provider account',
    description: 'Read the current provider account profile.',
    platform: 'PROVIDER',
    category: 'Provider Account',
    resource: 'provider-account',
    action: 'read',
    riskLevel: 'LOW',
    isAssignable: true,
  },
  {
    code: 'provider-account:update',
    name: 'Update provider account',
    description: 'Update provider account profile fields.',
    platform: 'PROVIDER',
    category: 'Provider Account',
    resource: 'provider-account',
    action: 'update',
    riskLevel: 'MEDIUM',
    isAssignable: true,
  },
  {
    code: 'property:read',
    name: 'Read provider properties',
    description: 'Read and list properties owned by the current provider.',
    platform: 'PROVIDER',
    category: 'Property',
    resource: 'property',
    action: 'read',
    riskLevel: 'LOW',
    isAssignable: true,
  },
  {
    code: 'property:create',
    name: 'Create property',
    description: 'Create a new property for the current provider.',
    platform: 'PROVIDER',
    category: 'Property',
    resource: 'property',
    action: 'create',
    riskLevel: 'MEDIUM',
    isAssignable: true,
  },
  {
    code: 'property:update',
    name: 'Update property',
    description: 'Update an existing property owned by the current provider.',
    platform: 'PROVIDER',
    category: 'Property',
    resource: 'property',
    action: 'update',
    riskLevel: 'MEDIUM',
    isAssignable: true,
  },
  {
    code: 'property:archive',
    name: 'Archive property',
    description:
      'Soft-delete (archive) a property owned by the current provider.',
    platform: 'PROVIDER',
    category: 'Property',
    resource: 'property',
    action: 'archive',
    riskLevel: 'MEDIUM',
    isAssignable: true,
  },
  {
    code: 'listing:read',
    name: 'Read provider listings',
    description: 'Read and list listings owned by the current provider.',
    platform: 'PROVIDER',
    category: 'Listing',
    resource: 'listing',
    action: 'read',
    riskLevel: 'LOW',
    isAssignable: true,
  },
  {
    code: 'listing:create',
    name: 'Create listing',
    description: 'Create a draft listing from a provider-owned property.',
    platform: 'PROVIDER',
    category: 'Listing',
    resource: 'listing',
    action: 'create',
    riskLevel: 'MEDIUM',
    isAssignable: true,
  },
  {
    code: 'listing:publish',
    name: 'Publish listing',
    description: 'Publish a draft listing owned by the current provider.',
    platform: 'PROVIDER',
    category: 'Listing',
    resource: 'listing',
    action: 'publish',
    riskLevel: 'MEDIUM',
    isAssignable: true,
  },
  {
    code: 'listing:archive',
    name: 'Archive listing',
    description: 'Archive a listing owned by the current provider.',
    platform: 'PROVIDER',
    category: 'Listing',
    resource: 'listing',
    action: 'archive',
    riskLevel: 'MEDIUM',
    isAssignable: true,
  },
] as const;

/** Provider capabilities used by the current Property and Listing boundaries. */
export type ProviderPermissionCode =
  (typeof PROVIDER_PERMISSION_REGISTRY)[number]['code'];
